# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ancandi's homepage
tagline:          'Hellos!'
description:      'Trying to get better at roblox stuff. Made by <a href="https://www.youtube.com/@and1exe" target="_blank">@and1</a>.'
url:              https://www.youtube.com/@and1exe
baseurl:          /

author:
  name:           'ancandi (and1)'
  url:            x.com/and1exe

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ancandi
