title: "ancandi's homepage"
description: "Trying to get better at Roblox stuff."
url: "https://ancandi.github.io"
baseurl: ""
lang: en
timezone: Asia/Taipei

author:
  name: "ancandi (and1)"
  url: "https://x.com/and1exe"

social:
  youtube: "https://www.youtube.com/@and1exe"
  github: "https://github.com/ancandi"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: default
